---
title: "Visualization PartI"
author: "ymmyz"
date: "10/3/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggridges)
```

```{r data_import, cache = TRUE}
library(rnoaa)

weather_df = 
  rnoaa::meteo_pull_monitors(c("USW00094728", "USC00519397", "USS0023B17S"),
                      var = c("PRCP", "TMIN", "TMAX"), 
                      date_min = "2017-01-01",
                      date_max = "2017-12-31") %>%
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY", 
                      USC00519397 = "Waikiki_HA",
                      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
weather_df
```

## Start a plot

Blank plot

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax))
```

Scatterplot

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point()
```

Only with data with CentralPark_NY

```{r}
weather_df %>% 
  filter(name == "CentralPark_NY") %>% 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point()
```

create and save a plot

```{r}
weather_sp = 
  ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point()
```

## More plot options

Add an aesthetic

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name))
```

Add a geom

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name)) + 
  geom_smooth(se = FALSE)
```

Add some options

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = 0.4) + 
  geom_smooth(se = FALSE)
```

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax, color = name)) +   # here, color = name applies for all the geom down there
  geom_point(alpha = 0.4) + 
  geom_smooth(se = FALSE)
```

Facetting ...

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = 0.4) + 
  geom_smooth(se = FALSE) +
  facet_grid( ~ name)   # Create seperate plots according to the name variable
```


A more interesting plot

```{r}
ggplot(weather_df, aes(x = date, y = tmax, color = name, size = prcp)) +
  geom_point() +
  geom_smooth(se = FALSE) +
  facet_grid( ~ name)
```

## Learning Assessment

```{r}
ggplot(weather_df) + geom_point(aes(x = tmax, y = tmin), color = "blue")
ggplot(weather_df) + geom_point(aes(x = tmax, y = tmin, color = "blue")) # Try to find a variable called blue, but cannot find one, so ggplot just create "blue" everywhere and color geom according to it
```

## Univariate plots

Histograms

```{r}
ggplot(weather_df, aes(x = tmax)) +
  geom_histogram() # Shows the distribution of tmax
```

```{r}
ggplot(weather_df, aes(x = tmax, fill = name)) +
  geom_histogram()
```

```{r}
ggplot(weather_df, aes(x = tmax, fill = name)) + #fill is a kind of color, fill everything under the curve
  geom_density(alpha = 0.4)
```

Boxplots 

```{r}
ggplot(weather_df, aes(x = name, y = tmax)) +
  geom_violin()
```

```{r}
ggplot(weather_df, aes(x = tmax, y = name)) +
  geom_density_ridges()
```

